### ISSUE TITLE
After compiling from source make does not work for Rocq 9.0.0

### ISSUE THREAD

**Issue by bfurmane** [Karmaki/coq-dpdgraph#144]
Hello,

I use Rocq 9.0.0 and got an error after compiling from source
File "graphdepend.mlg", line 260, characters 6-28:
Error: Unbound value Nametab.path_of_module
Hint: Did you mean dirpath_of_module or path_of_modtype?
make[1]: *** [Make_coq:735: graphdepend.cmx] Error 2

the important snippet:
let locate_mp_dirpath qid =
  try Nametab.path_of_module (Nametab.locate_module qid)
  with Not_found ->
    let msg = str "Unknown module" ++ spc() ++ Libnames.pr_qualid qid in
    CErrors.user_err ?loc:qid.CAst.loc msg

i changed it to
let locate_mp_dirpath qid =
  try Nametab.dirpath_of_module (Nametab.locate_module qid)
  with Not_found ->
    let msg = str "Unknown module" ++ spc() ++ Libnames.pr_qualid qid in
    CErrors.user_err ?loc:qid.CAst.loc msg

and now I can make and make install. make -s test also works

I'd rather send it as an issue since I am not maintainer of the code.

Best wishes,
Bart.

**Comment by SkySkimmer** [comment]
The default branch compiles with rocq master and is not expected to compile with any other version.
3a0df04d72539a6886c24b59dfcf2489e9a41b78 should work for 9.0.
The branch for 8.20 may also work with 9.0 but the tests won't.
