### ISSUE TITLE
coq 8.6 compatibility

### ISSUE THREAD

**Issue by vzaliva** [Karmaki/coq-dpdgraph#11]
Does not compile under Coq-8.6:

```
# make[1]: Leaving directory '/home/lord/.opam/4.04.0.coq.8.6/build/coq-dpdgraph.0.6'
# Makefile:59: recipe for target 'dpdgraph.cmxs' failed
### stderr ###
# [...]
# - Use '... EXTEND Searchdepend CLASSIFIED AS SIDEFF ...' if the new vernacular command alters the system state but not the parser nor it starts a proof or ends one;
# - Use '... EXTEND Searchdepend CLASSIFIED BY f ...' to specify a global function f.  The function f will be called passing "Searchdepend" as the only argument;
# - Add a specific classifier in each clause using the syntax:
# '[...] => [ f ] -> [...]'. 
# Specific classifiers have precedence over global classifiers. Only one classifier is called.
# 
# File "searchdepend.ml4", line 93, characters 6-14:
# Error: Unbound value Pp.msgnl
# make[1]: *** [searchdepend.cmx] Error 2
# make: *** [dpdgraph.cmxs] Error 2

```

**Comment by ybertot** [comment]
for information: I am working on it, I should be able to commit a version that compiles with coq-8.6
any time soon.

**Comment by ybertot** [comment]
The github version should now be coq-8.6 compatible.  It should also be available through opam.
